title: hwshqtb's blog & wiki
author: hwshqtb
email: 1353736321@qq.com
social_links:
  - title: bilibili
    url: "https://space.bilibili.com/272692391"
  - title: github
    url: "https://github.com/hwshqtb"
license: 除非特别注明，本页内容采用以下授权方式：<a href="https://creativecommons.org/licenses/by-nd/4.0/">CC BY-ND 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width:1em;max-height:1em;margin-left:.2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width:1em;max-height:1em;margin-left:.2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nd.svg" alt="" style="max-width:1em;max-height:1em;margin-left:.2em;">

permalink: /:categories/:title:output_ext

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

date_format: "%Y年%m月%d日"

markdown: kramdown

kramdown:
  math_engine: null

